plugins {
    id 'fabric-loom' version "${fabric_loom_version}"
}

version = "${version}+mc.${minecraft_version}"
group = project.property('group')

repositories {
    mavenCentral()
    maven { url 'https://maven.fabricmc.net/' }
}

loom {
    splitEnvironmentSourceSets()
    mods {
        'anticheat' {
            sourceSet sourceSets.main
            sourceSet sourceSets.client
        }
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.property('minecraft_version')}"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${project.property('fabric_loader_version')}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.property('fabric_api_version')}"
    implementation project(':core')
}
